"""Shared helpers for nice!view slideshow frames (68x140 portrait, 1-bit).

Frames are numpy bool arrays shaped (140, 68), True = white pixel.
Each animation is exported as <name>.c/.h containing:
  - static frame descriptors (stored rotated 90deg CW as 140x68 INDEXED_1BIT,
    the same layout as the original hammerbeam art.c)
  - const lv_img_dsc_t *const <name>_imgs[]   the frame table, kept in flash
  - <NAME>_FRAME_COUNT in the header
"""
import os
import numpy as np
from PIL import Image

W, H = 68, 140
yy, xx = np.mgrid[0:H, 0:W]
_B = np.array([[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]]) / 16.0
BAYER = np.tile(_B, (H // 4 + 1, W // 4 + 1))[:H, :W]


def disc(cx, cy, r):
    return (xx - cx) ** 2 + (yy - cy) ** 2 <= r * r


def rect(x0, y0, x1, y1):
    return (xx >= x0) & (xx <= x1) & (yy >= y0) & (yy <= y1)


def thick_line(x0, y0, x1, y1, w):
    dx, dy = x1 - x0, y1 - y0
    L2 = dx * dx + dy * dy or 1
    t = np.clip(((xx - x0) * dx + (yy - y0) * dy) / L2, 0, 1)
    px, py = x0 + t * dx, y0 + t * dy
    return (xx - px) ** 2 + (yy - py) ** 2 <= (w / 2) ** 2


def sprite(rows, x, y):
    """Stamp an ASCII sprite: 'X' = white, 'o' = force black, '.' = transparent."""
    on = np.zeros((H, W), bool)
    off = np.zeros((H, W), bool)
    for j, row in enumerate(rows):
        for i, c in enumerate(row):
            X, Y = x + i, y + j
            if 0 <= X < W and 0 <= Y < H:
                if c == "X":
                    on[Y, X] = True
                elif c == "o":
                    off[Y, X] = True
    return on, off


def _c_frames(frames, name):
    out = []
    for i, f in enumerate(frames, 1):
        stored = np.rot90(f, k=-1)            # portrait -> stored 140x68 (display rotates it back)
        rows, cols = stored.shape
        rb = (cols + 7) // 8
        packed = np.packbits(np.pad(stored, ((0, 0), (0, rb * 8 - cols))).astype(np.uint8), axis=1)
        out.append(f"static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {name}{i}_map[] = {{")
        out += ["#if CONFIG_NICE_VIEW_WIDGET_INVERTED",
                "    0xff, 0xff, 0xff, 0xff, /*Color of index 0*/",
                "    0x00, 0x00, 0x00, 0xff, /*Color of index 1*/",
                "#else",
                "    0x00, 0x00, 0x00, 0xff, /*Color of index 0*/",
                "    0xff, 0xff, 0xff, 0xff, /*Color of index 1*/",
                "#endif"]
        for r in packed:
            out.append("    " + ", ".join(f"0x{b:02x}" for b in r) + ",")
        out += ["};", "",
                f"static const lv_img_dsc_t {name}{i} = {{",
                "    .header.cf = LV_IMG_CF_INDEXED_1BIT,",
                "    .header.always_zero = 0,",
                "    .header.reserved = 0,",
                f"    .header.w = {cols},",
                f"    .header.h = {rows},",
                f"    .data_size = {8 + packed.size},",
                f"    .data = {name}{i}_map,",
                "};", ""]
    return out


def export(name, frames, c_dir, preview_dir, preview_ms=150):
    """Write <name>.c/.h into c_dir and PNG frames, a GIF preview and a contact sheet into preview_dir."""
    os.makedirs(os.path.join(preview_dir, "frames", name), exist_ok=True)
    big = []
    for i, f in enumerate(frames, 1):
        im = Image.fromarray(np.where(f, 255, 0).astype(np.uint8))
        im.convert("1").save(os.path.join(preview_dir, "frames", name, f"{name}_{i:02d}.png"))
        big.append(im.resize((W * 4, H * 4), Image.NEAREST))
    big[0].save(os.path.join(preview_dir, f"{name}_preview.gif"), save_all=True,
                append_images=big[1:], duration=preview_ms, loop=0)
    cols = 10
    rws = (len(frames) + cols - 1) // cols
    sheet = Image.new("L", (cols * (W + 4), rws * (H + 4)), 128)
    for i, f in enumerate(frames):
        sheet.paste(Image.fromarray(np.where(f, 255, 0).astype(np.uint8)),
                    ((i % cols) * (W + 4), (i // cols) * (H + 4)))
    sheet.resize((sheet.width * 2, sheet.height * 2), Image.NEAREST).save(
        os.path.join(preview_dir, f"{name}_sheet.png"))

    n = len(frames)
    up = name.upper()
    c = ["/*",
         f" * {name}: {n} frames, 68x140 portrait, stored rotated as 140x68 LV_IMG_CF_INDEXED_1BIT.",
         " * Generated by tools/animations - edit the generator, not this file.",
         " */", "",
         "#include <lvgl.h>", f'#include "{name}.h"', "",
         "#ifndef LV_ATTRIBUTE_MEM_ALIGN", "#define LV_ATTRIBUTE_MEM_ALIGN", "#endif",
         "#ifndef LV_ATTRIBUTE_LARGE_CONST", "#define LV_ATTRIBUTE_LARGE_CONST", "#endif", ""]
    c += _c_frames(frames, name)
    c.append("/* Pointer table lives in flash too (const pointers to const descriptors). */")
    c.append(f"const lv_img_dsc_t *const {name}_imgs[{up}_FRAME_COUNT] = {{")
    c += [f"    &{name}{i}," for i in range(1, n + 1)]
    c.append("};")
    with open(os.path.join(c_dir, f"{name}.c"), "w") as fh:
        fh.write("\n".join(c) + "\n")
    with open(os.path.join(c_dir, f"{name}.h"), "w") as fh:
        fh.write(f"#pragma once\n\n#include <lvgl.h>\n\n#define {up}_FRAME_COUNT {n}\n\n"
                 f"extern const lv_img_dsc_t *const {name}_imgs[{up}_FRAME_COUNT];\n")
